server:
  port: 8080

spring:
  application:
    name: lascarinosas

  datasource:
    url: jdbc:postgresql://localhost:5432/lascarinosas_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Keycloak JWT validation
  # Spring will fetch the public key from Keycloak to validate tokens
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/lascarinosas-realm